[[main]]
  identifier = "Posts"
  name = "posts"
  url = "/posts"
  weight = 1
[[main]]
  identifier = "Blender"
  name = "blender"
  url = "/blender"
  weight = 3
[[main]]
  identifier = "Projects"
  name = "projects"
  url = "/projects"
  weight = 4
[[main]]
  identifier = "About"
  name = "about"
  url = "/about"
  weight = 5